### PR TITLE
Setup husky with pre commit hook

### PR DESCRIPTION
**Pull request by RocktimSaikia**
I separated the lint script and added it to the `pre-commit` hook along with the test script. I was not sure about adding the lint script to the GitHub actions so didn't add but if you want to add it there I will just add it there too.
@talentlessguy

### CODE REVIEW

**Comment by talentlessguy** [comment]
LGTM, merging!

**Comment by talentlessguy** [comment]
About the lint script, it's uneeded in actions imo. The action is used for checking if packages build with no errors and that tests pass.

**Comment by RocktimSaikia** [comment]
@talentlessguy Yes that was my initial thought too .

**Comment by talentlessguy** [comment]
@all-contributors please add RocktimSaikia for infra

**Pull request merged**
