### PR TITLE
Ability to send null .json responses

### PR DESCRIPTION
**Pull request by calumk**
this should fix the issue https://github.com/talentlessguy/tinyhttp/issues/223 where res.json() cant send null responses.

### CODE REVIEW

**Comment by talentlessguy** [comment]
The build is failing, please fix

**Review by calumk — COMMENTED** [review]
type of expects string

**Comment by calumk** [comment]
@talentlessguy  code coverage checks are failing but i don't know how to resolve that

**Comment by talentlessguy** [comment]
Looks good now,

could you also please add tests for sending `null`? in `__tests__/modules/send.test.ts`

**Comment by talentlessguy** [comment]
Landed in 344a8ae79c72a803dba5b34614d5272c432bbf8c

closing

**Pull request closed without merging**
