### PR TITLE
Added `timestamp` to logger and created logger properties interface

### PR DESCRIPTION
**Pull request by Arnovsky**
resolves: #11 

* Formatting timestamp with `dayjs`.
* Updated package version to `0.3.0` since it contains breaking changes.
* Added test that checks if the logger is being called.

Please let me know if these bullets are fine!

### CODE REVIEW

**Comment by talentlessguy** [comment]
@Arnovsky  Could you please show a usage example? Want to see how it works in practise :D

**Comment by Arnovsky** [comment]
The API is described in the PR (I have edited the readme.md).

And the log messages look like this (by default):
`15:28:10 - GET 404 Not Found /favicon.ico`

**Comment by talentlessguy** [comment]
@Arnovsky hmmm ok, the build fails tho, because u have (probably) broken lockfile.

Could you please `git pull`, then `rm -rf node_modules` and `pnpm install`? so the proper lockfile will generate

**Comment by talentlessguy** [comment]
@Arnovsky pnpm is taking very long to install :thinking: 

mb u messed up somewhere?

**Comment by Arnovsky** [comment]
Not sure, I deleted node_modules and ran `pnpm install && pnpm recursive install` anything else I should do?

**Comment by talentlessguy** [comment]
@Arnovsky 

Nice, it's working now.

Could you please create a "mw" folder and put your logger test there?

**Comment by talentlessguy** [comment]
LGTM. mergin'

**Comment by talentlessguy** [comment]
@all-contributors please add Arnovsky for plugin

**Pull request merged**
