### PR TITLE
#140 added tests for req

### PR DESCRIPTION
**Pull request by MaurizioPz**
This PR adds the test listed on #140 

but the  test 'Should ignore charset' is ignored because right now it doesn't pass. I may have misinterpreted the desired test, but as of right now https://github.com/jshttp/media-typer seems to be using a regex that doesn't handle charset

### CODE REVIEW

**Comment by talentlessguy** [comment]
@MaurizioPz by "should ignore charset" for `req.is` I meant that if you send a `Content-Type` that includes a charset, it must ignore it and check for the MIME type only

**Comment by MaurizioPz** [comment]
Well than there's a bug right now, because it sounds like you are expecting this test to pass and it doesn't

```
    it('should ignore charset', async () => {
      const app = runServer((req, res) => {
        expect(reqIs(req)('text/html')).toBe('text/html')
        res.end()
      })
      await makeFetch(app)('/', {
        headers: {
          'Content-Type': 'text/html; charset=UTF-8',
        },
      })
      expect.assertions(1)
    })
```

**Comment by BRA1L0R** [comment]
@MaurizioPz i've investigated on the issue and pointed it out in #150. You can work on it if you want as it is very easy to fix but also relatively important.

**Comment by talentlessguy** [comment]
@MaurizioPz could you pls fix the conflict so we can merge this?

**Comment by talentlessguy** [comment]
nice, now it looks good

merging

**Comment by talentlessguy** [comment]
@all-contributors add @MaurizioPz for test

**Pull request merged**
