### PR TITLE
feat(cors): support for multiple origin using array and regex

### PR DESCRIPTION
**Pull request by aldy505**
regarding #224 

see [this repo](https://github.com/aldy505/tinyhttp-cors-test) for sample test and usage

### CODE REVIEW

**Comment by talentlessguy** [comment]
Could you also please write a few tests in `__tests__/mw/cors.test.ts` for regex matching? (so that the coverage doesn't drop)

**Comment by talentlessguy** [comment]
@aldy505 there is a merge conflict... could you please fix that?

**Comment by aldy505** [comment]
@talentlessguy I don't know why it's still conflicting. I think it'd be fine if you resolve the conflicts with my files. Let me know if there are other concerns.

**Comment by talentlessguy** [comment]
@aldy505 try to pull from master

**Comment by aldy505** [comment]
@talentlessguy this should fix everything. I've also bumped the version.

**Comment by talentlessguy** [comment]
@aldy505 u forgot to run prettier

**Comment by aldy505** [comment]
@talentlessguy everything should be good now

**Comment by talentlessguy** [comment]
@all-contributors add @aldy505 for code

**Comment by talentlessguy** [comment]
@allcontributors add @aldy505 for code

**Comment by talentlessguy** [comment]
@aldy505 `@tinyhttp/cors` is release with multiple origins support!

Install:

```sh
pnpm i @tinyhttp/cors@1.1.5
```

**Pull request merged**
