### PR TITLE
Add emoji options for logger middleware

### LINKED ISSUE #51: Add badges option to @tinyhttp/logger
**Is your feature request related to a problem? Please describe.**

It adds emoji badges for better readability

**Describe the solution you'd like**

Add `badges` setting with 2 sub-settings to be used like this:

```js
app.use(logger({ badges: { emoji: true, captions: false }))
```

Default values are both false - if `badges: true` - only toggle emoji. if an object is present - check for the settings.

first setting toggles emoji badges, like this :warning:
second enables emoji alt text (in case emoji fails to display or just prefer the text instead), like this: `warning`

here's a table of emoji / texts:

| emoji | text | status code |
|-----|-------|----------------|
|  :x: | Error  | 500 |
| :warning: | status message | 4XX (Except 404) |
| :ok: | OK | 2XX |
| :mag_right:  | Not Found | 404 |

Should be logged in the beginning:

```
🆗 GET 200 OK /css/shared.css
```

**Additional context**

[Zoya](https://github.com/WoLfulus/zoya) logger that has emoji:

image

### PR DESCRIPTION
**Pull request by ahmad-reza619**
This PR close #51 

Currently, i'm still implementing the emoji on my own, i will work on using https://github.com/bendrucker/http-status-emojis by tomorrow.

any review is very welcomed 😄

### CODE REVIEW

**Comment by talentlessguy** [comment]
@ahmad-reza619 looks nice, gonna merge once u replace it with emoji statuses

again sorry that I came up with it way too late, didn't know there was a module for this before

**Comment by ahmad-reza619** [comment]
It's fine @talentlessguy i learned a lot by just making these PR 👍 😄

**Comment by ahmad-reza619** [comment]
@talentlessguy so do i have to install the `http-status-emojis`? if so where should i install it? this is my first time dealing with monorepo 😅 . is it inside logger middleware directory or just the root is fine?

**Comment by talentlessguy** [comment]
@ahmad-reza619 go to packages/logger and install it there

**Comment by ahmad-reza619** [comment]
Can i import it in logger test? if i were to place it in logger?

**Comment by talentlessguy** [comment]
@ahmad-reza619 you can import any module in your test afaik, cuz it's a monorepo so everything gets installed in root

**Comment by talentlessguy** [comment]
anyways, it looks good, merging it

**Pull request merged**
