### PR TITLE
replaced colors with colorette

### PR DESCRIPTION
**Pull request by elianiva**
I've replaced `colors` package with `colorette` for `packages/logger`.

### CODE REVIEW

**Comment by talentlessguy** [comment]
@elianiva pls update the lockfile

**Comment by elianiva** [comment]
done

**Comment by talentlessguy** [comment]
you forgot to update the tests

**Comment by elianiva** [comment]
oopsie, done

**Comment by talentlessguy** [comment]
@elianiva hmmm the lockfile seems to cause conflicts. I think the best idea is to gitignore it forever

**Comment by talentlessguy** [comment]
just pull my latest commit and conflict will disappear

**Pull request merged**
